### ISSUE TITLE
Register it in bpkg to simplify installation

### ISSUE THREAD

**Issue by igorshubovych** [raylee/tldr#1]
Register it in bpkg to simplify installation for those weirdos who are using it.

http://www.bpkg.io/

**Comment by raylee** [comment]
Interesting, thanks for the link to bpkg, I never would have guessed bash had it's own package manager. After I address the other issues, I'll do so!

**Comment by revolter** [comment]
What about [brew](http://brew.sh)?

**Comment by raylee** [comment]
As bpkg.io is no more, I'm closing this. Homebrew is starting to be replaced with pkgx (from the same author), so for platforms where that can run, a compiled tldr client may be an easier choice. I can revisit this if y'all think I'm off-base.
