### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by j8r** [raylee/tldr#12]
The actual name can be confusing and doesn't sufficiently reflect the nature of this project — a shell script client to read tldr-pages. Furthermore the actual name `tldr` is the same as [the main repository](https://github.com/tldr-pages/tldr).

Therefore I propose to change the name to another one. Personnally I like well `tldr.sh`.
Everyone is welcomed to express its opinion and suggestions below.

Special thanks again to @raylee for his work on this project :)

See also:
#10 
[https://github.com/tldr-pages/tldr/issues/1109#issuecomment-255104786](https://github.com/tldr-pages/tldr/issues/1109#issuecomment-255104786)

**Comment by raylee** [comment]
I think there's nothing wrong with renaming the repository to tldr.sh, that option barely lost to tldr when I initially created the project on GitHub. That said, I don't think there's any issue with it sharing the same name as the main repository. Indeed, the reference version is also considering a name change, to tldr.sh as well.
