### ISSUE TITLE
Add bash completion with available commands

### ISSUE THREAD

**Issue by diegonz** [raylee/tldr#13]
I think it would be a nice idea to someway add bash completion to program names based on the index.json contents.

**Comment by cibinjoseph** [comment]
This should be possible by placing the following line in bashrc:
`complete -W "\'tr "{" "\n" < "$HOME/.config/tldr/index.json" | cut -d '"' -f4\'" tldr`
Unfortunately, the `'"'` after the `cut -d` command gives me trouble. Someone with knowledge on escaping single quotes in bash scripts should be able to figure it out.

**Comment by raylee** [comment]
adding
```bash
complete -W "$(tldr 2>/dev/null --list)" tldr
```
...to your startup script will do the right thing. I'll add this to the README. Thanks!
