### ISSUE TITLE
Use $XDG_CACHE_HOME instead of ~/.config

### ISSUE THREAD

**Issue by admirabilis** [raylee/tldr#23]
I had a look at `~/.config/tldr`, and none of the files there store user settings (and may ignored by daily backups). I propose using the standard directory for caches, which is `$XDG_CACHE_HOME`, or `~/.cache` if unset. With the current code:

    configdir=${XDG_CACHE_HOME:-$HOME/.cache}/tldr

**Comment by raylee** [comment]
Fixed.
