### ISSUE TITLE
correct files for BSD

### ISSUE THREAD

**Issue by henningninneh** [raylee/tldr#24]
Hi,

thanks for this useful script!

In order to make it run on FreeBSD, I had to adjust two things:

- Install into '/usr/local/bin' rather than '~/bin'
- Edit the first (shebang) line of the script so it reads '#!/usr/local/bin/bash'

Obviously, bash needs to be installed and run. The default on FreeBSD is csh.

Perhaps you could just link to this issue in your readme.

Best
H

**Comment by raylee** [comment]
Thanks for the feedback!

If you have a little time, could you try something for me? If you change the first line to:
`#!/usr/bin/env bash`
does that also work?

I'll update the readme to mention that this script assumes `~/bin` is in `$PATH`.

**Comment by henningninneh** [comment]
Hi,

sorry, if I change the first line to `#!/usr/bin/env bash` and run the script, I get "defect interpreter: No such file or directory".

**Comment by raylee** [comment]
The tldr script is now POSIX compliant, and should run on any default POSIX shell.
