### ISSUE TITLE
Unnecessary info after updating pages cache

### ISSUE THREAD

**Issue by Wesalius** [raylee/tldr#26]
After a user runs `tldr -u`, tldr shows the same output as when running `tldr` which is unnecessary. Simple "Update is done" or something similar would be sufficient. I am reporting because it confused me couple of times thinking the update didnt go through.

**Comment by raylee** [comment]
Thanks for the feedback, I've added your suggestion to the code.

**Comment by raylee** [comment]
A question for you @Wesalius ? Would you suggest the help be entirely suppressed in that case? The original intent was to allow usage such as `tldr -u chsh` which would update and print a help page. Which means if the argument is missing, the help appears.

I could suppress the help in that situation, or simply exit after updating. Which would be the behavior you'd expect?

**Comment by Wesalius** [comment]
What would be the difference between suppressing help and exiting? I mean both wouldnt print anything to stdout, or did I get your question wrong?
