### ISSUE TITLE
POSIX compliance

### ISSUE THREAD

**Issue by raylee** [raylee/tldr#31]
Make tldr POSIX compliant such that it can be used with a bare /bin/sh implementation. Items to fix:

- `[[ ]]` vs `[ ]`
- indexing strings (eg `${var:2}`)
- replacing `echo` variations with `printf`
- etc.

This will cover most of the items from `checkbashisms -f ~/bin/tldr` and https://github.com/koalaman/shellcheck

**Comment by sethwoodworth** [comment]
@becomesaflame and I have an old branch where we were walking through all of the `shellcheck` list of bashisms.
How may we contribute to this feature?  If we convert a range of lines from the current script, would you accept a partial PR of the conversion, or could we contribute to a branch? (third option, you can do the conversion if you prefer and we can start working on tab completion :D )

**Comment by raylee** [comment]
It would be nice to see your take on it. I've started a list of translations for the current code which I'm going to turn into functions. eg, 

```bash
firstchar() {
  last="${1#?}"
  printf "${1%$last}"
}

# via http://www.etalabs.net/sh_tricks.html
fnmatch () { case "$2" in $1) return 0 ;; *) return 1 ;; esac ; }
# example:
if fnmatch 'a??*' "$var" ; then ... ; fi
```

Partial PRs are fine, we can work in a branch if that ends up being necessary or useful.

For tab completion, were you thinking of anything more than what I added to the README?

```bash
complete -W "$(tldr 2>/dev/null --list)" tldr
```

**Comment by raylee** [comment]
Looks like this is the branch?

https://github.com/becomesaflame/tldr/commit/db8f9dcd6f066fcd7ab8cd283381119e88ae8730

**Comment by raylee** [comment]
I've pushed a new branch with all the POSIX compliance work here: https://github.com/raylee/tldr/tree/posix . `checkbashisms` now reports tldr as clean of an bash specific behaviors.

I still need to test it on a variety of systems before I merge it into master. But for anyone who is curious...

**Comment by raylee** [comment]
I've addressed this with https://github.com/raylee/tldr/commit/ded95ab823662acc3075d32563a84b5a0abdd9d6
