### ISSUE TITLE
A new helpful feature:Command-Description

### ISSUE THREAD

**Issue by LichaowuX-X** [raylee/tldr#38]
when we type "tldr ps", tldr shows you some use cases,then just use it,many one knows that's a shortcut-like thing for "Process Status".But some command would confuse developer from Non-English-Native country like me,so i am looking forward to some feature,once you type "tldr ps",some short hints could show me what does it mean,it would help me keep it in mind deeply.Thx and Sincerely

**Comment by raylee** [comment]
Hello! The tldr project is adding translations of pages to new languages. I will add language support as time permits.

In the meantime, check the top lines that are printed from `tldr ps`. You will see "Information about running processes." near the top, which explains the command itself.

If you have the latest tldr from this repository and [fzf](https://github.com/junegunn/fzf) installed, you can do this:

`tldr --list | fzf --preview 'tldr {}'`

That will give you an interactive list of all commands, and you can go through them to see what they are.

**Comment by BachoSeven** [comment]
That is once again a really nice use of fzf, thanks for the suggestion!
