### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by bl-ue** [raylee/tldr#45]
Hello, I'm from @tldr-pages.

I'd like to know whether or not you're still interested in working ont his project @raylee.  It's perfectly fine if you aren't, (no pressure intended! 💯) but if you're not I'd like to mark is not being maintained on [our readme](https://github.com/tldr-pages/tldr#how-do-i-use-it) because that list is growing rather unwieldy, see https://github.com/tldr-pages/tldr/issues/4044 for details.

Also, I'm not sure what the difference is between this and a popular for of this project, [pepa65/tldr-bash-client](https://github.com/pepa65/tldr-bash-client), other than this is tldr-**sh**-client and that's tldr-**bash**-client.

Thank you!

**Comment by bl-ue** [comment]
So I'm guessing the answer is pretty much, no.

**Comment by raylee** [comment]
Hello Mr. Bl-ue, this is maintained except for recently when I've been slowly recovering from the plague. I'll address your comments in a bit.

**Comment by bl-ue** [comment]
Ah, I see! Thank you for responding!  Okay, I'll keep this client in our list then. 👍🏻

**Comment by raylee** [comment]
I see your point about the list of clients getting unwieldy. To answer your question, pepa65 forked this repo a long time ago to make his version (which is fine). He had other ideas about what the defaults and code should look like, and (I presume) felt it better to work on his own version than address my review comments on his PRs.

More importantly, this version works in POSIX shells, such as /bin/sh or /bin/dash. It uses no bash extensions. My intent with this version is to have a a dependency-free tldr client which could be included in a base Debian or Ubuntu distro. /bin/bash is great, but not for core utils such as tldr.

I need to review the [latest spec](https://github.com/tldr-pages/tldr/blob/main/CLIENT-SPECIFICATION.md) and see what's new. If you have recommendations for keeping up to date on the core project's changes other than the spec, I'd appreciate a pointer.

**Comment by bl-ue** [comment]
Nope, the project looks good besides the spec updates it needs.  Nice job!

I'm working on cleaning up the list of clients and structuring it, see https://github.com/tldr-pages/tldr/issues/6163.  If I see this repo has recent commits, that's enough to keep it on the list.  

It doesn't really matter how many clients there are as long as we can control them and recycle the dead ones ;)

Thank you for answering my questions; I'll close this issue now.
