### ISSUE TITLE
Local override paths were removed

### ISSUE THREAD

**Issue by 5u623l20** [raylee/tldr#51]
Earlier there was an option to have local customized md files but this was removed in d1b8444e6a005e0515580bed6ff22b7a7ce657be

Is there any way to return it back? In case for your reference this was the commit where local custom scripts supports were added.
https://github.com/raylee/tldr-sh-client/commit/92e0545048b9bb702aca62b7df30fe299defb5c9

**Comment by raylee** [comment]
Sure. Is re-adding this sufficient or do you have suggestions for something else that would better fit your workflow?
