### ISSUE TITLE
support for busybox unzip

### ISSUE THREAD

**Issue by bdantas** [raylee/tldr#52]
Hi, raylee. I'm on a system that uses BusyBox for most userland commands, including `unzip`. `curl` is installed.

The `-u` flag on line 263 is causing problems for me because BusyBox `unzip` does not support this option:
```
unzip: invalid option -- 'u'
BusyBox v1.36.1 (2023-12-24 14:06:38 UTC) multi-call binary.

Usage: unzip [-lnojpqK] FILE[.zip] [FILE]... [-x FILE]... [-d DIR]

Extract FILEs from ZIP archive

	-l	List contents (with -q for short form)
	-n	Never overwrite files (default: ask)
	-o	Overwrite
	-j	Do not restore paths
	-p	Write to stdout
	-t	Test
	-q	Quiet
	-K	Do not clear SUID bit
	-x FILE	Exclude FILEs
	-d DIR	Extract into DIR
```
Do you have interest in refactoring the `update_tldr_cache` function so that it works with BusyBox `unzip` as well as with the full-fledged `unzip`?

**Comment by bdantas** [comment]
Never mind. I thought about this some more and I think getting rid of the `-u` flag would complicate the script unnecessarily. I installed `unzip` and now the script works as advertised.

This is a beautifully minimalistic option compared to all the other tldr clients available. Kudos.

**Comment by raylee** [comment]
Thanks for the kind words. I have a few busybox systems in my life now though they aren't connected to the 'net. Checking on one of them it looks like everything is working if you simply remove the `-u` option, as `-o` is also provided. I'd have to check the history and double-check all the platforms before I remove that in the main branch, though.

On an embedded system where you might have other users and custom code running, you may find the change mentioned in issue #51 handy as well. It's kind of a nice way to ship lightweight custom documentation on constrained systems, which was the original intent of this script.

Anyway, I'm glad it's useful!

**Comment by bdantas** [comment]
Hi raylee. Thanks for the tip of simply removing the `-u` option. I can confirm that removing the `-u` option has no ill effects, so I was able to uninstall `unzip` from my BusyBox-powered system and your script is still working well, including dowloading `tldr.zip` and updating the cache when appropriate (i.e., when `cache_days` has been exceeded).

Happy hacking!
